[phases.setup]
nixPkgs = ["nodejs_20", "chromium"]

[phases.install]
cmds = ["npm install"]

[variables]
PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH = "/nix/var/nix/profiles/default/bin/chromium"
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1"
