[phases.setup]
nixPkgs = ["chromium"]

[phases.install]
cmds = ["npm install", "PLAYWRIGHT_BROWSERS_PATH=/app/pw-browsers npx playwright install chromium"]

[variables]
PLAYWRIGHT_BROWSERS_PATH = "/app/pw-browsers"
